[package]
name = "iot-simulator-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iot-simulator-api = { path = "../iot-simulator-api", version = "*" }
libloading = "0.7.3"
ron = "0.7"
